export const SITE = {
  name: "Lov'Ceylon",
  legalName: "Lov'Ceylon Photography",
  url: "https://lovceylon.com",
  phone: "+94 777 807 619",
  phoneTel: "+94777807619",
  email: "info@lceylon.com",
  location: "Colombo, Sri Lanka",
  whatsapp: "https://wa.me/94777807619",
  tagline: "Wedding, homecoming & portrait photography in Sri Lanka",
  description:
    "Lov'Ceylon is a Sri Lankan photography studio crafting timeless wedding, homecoming & pre-shoot photography in Colombo. Explore our packages, prices & portfolio.",
  keywords: [
    "Lov'Ceylon",
    "Lov'Ceylon Photography",
    "Love Ceylon Photography",
    "wedding photography Sri Lanka",
    "Sri Lankan wedding photography",
    "best wedding photography Sri Lanka",
    "photography Sri Lanka",
    "Sri Lankan photography packages price",
    "wedding photography packages Sri Lanka",
    "wedding photographer Colombo",
    "homecoming photography Sri Lanka",
    "pre-shoot photography Sri Lanka",
    "portrait photography Sri Lanka",
    "Colombo wedding photographer",
  ],
} as const;
